change sign and repo to vscodium
Tiryoh/docker-ros2-desktop-vnc pull request #148
Opened 2024-03-31 03:22 UTC by sbarcelona11

2024-03-31 08:08 UTC, Tiryoh requested changes

2024-03-31 08:08 UTC, Tiryoh commented on foxy/Dockerfile
>      | dd of=/usr/share/keyrings/vscodium-archive-keyring.gpg && \
```suggestion
    -O /usr/share/keyrings/vscodium-archive-keyring.asc && \
```

2024-03-31 08:08 UTC, Tiryoh commented on foxy/Dockerfile
>      | dd of=/usr/share/keyrings/vscodium-archive-keyring.gpg && \
Hi @sbarcelona11 , Thanks for the pull request.

Could you fix these lines to make it work?

2024-03-31 08:10 UTC, Tiryoh commented on humble/Dockerfile
>      | dd of=/usr/share/keyrings/vscodium-archive-keyring.gpg && \
```suggestion
    -O /usr/share/keyrings/vscodium-archive-keyring.asc && \
```

2024-03-31 08:10 UTC, Tiryoh commented on iron/Dockerfile
>      | dd of=/usr/share/keyrings/vscodium-archive-keyring.gpg && \
```suggestion
    -O /usr/share/keyrings/vscodium-archive-keyring.asc && \
```

2024-03-31 08:10 UTC, Tiryoh commented on rolling/Dockerfile
>      | dd of=/usr/share/keyrings/vscodium-archive-keyring.gpg && \
```suggestion
    -O /usr/share/keyrings/vscodium-archive-keyring.asc && \
```

2024-03-31 17:54 UTC, sbarcelona11 commented on foxy/Dockerfile
>      | dd of=/usr/share/keyrings/vscodium-archive-keyring.gpg && \
fixed

2024-03-31 17:54 UTC, sbarcelona11 commented on iron/Dockerfile
>      | dd of=/usr/share/keyrings/vscodium-archive-keyring.gpg && \
fixed

2024-03-31 17:55 UTC, sbarcelona11 commented on humble/Dockerfile
>      | dd of=/usr/share/keyrings/vscodium-archive-keyring.gpg && \
fixed

2024-03-31 17:55 UTC, sbarcelona11 commented on rolling/Dockerfile
>      | dd of=/usr/share/keyrings/vscodium-archive-keyring.gpg && \
fixed

2024-04-04 00:10 UTC, Tiryoh commented
Hi @sbarcelona11, thanks for the fix.
I pushed a commit to fix some typos in the commit [412abf6](https://github.com/Tiryoh/docker-ros2-desktop-vnc/pull/148/commits/412abf61c840d67a77e2e9daef6c33b24b0ca278).

2024-04-04 00:13 UTC, sbarcelona11 commented
@Tiryoh Thanks to you! I'm using your image to work with ROS2 and Robotics. I would like you to create a version with GPU support. Can you?

2024-04-05 04:58 UTC, merged